---
- hosts: all
  vars:
    users:
      - name: ivoputzer
        comment: Ivo von Putzer Reibegg
        password: $5$CxNlRUfkip1zf1Gw$d8jz.HFz/wDe.42VMOi1No2mEpRcCEIUYDJj7QAGv81
  roles:
    - role: users

