- name: Add users with primary group 'sudo'
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    password: "{{ item.password }}"
    group: sudo
    shell: /bin/bash
    create_home: true
  with_items: "{{ users }}"

- name: Add authorized_keys without validating the certificates
  authorized_key:
    user: "{{  item.name }}"
    state: present
    key: "https://github.com/{{ item.name }}.keys"
    validate_certs: false
  with_items: "{{ users }}"
