---
- name: Ensure obsolete docker versions are not installed
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure docker apt dependencies are present
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - python3-pip
    state: present

- name: Ensure docker python dependencies are present
  pip:
    name: docker
    executable: pip3

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu cosmic test
    state: present
    update_cache: true

- name: Install docker
  package:
    name: docker-ce
    state: present
  notify: restart docker

- name: Ensure containerd service directory exists
  file:
    path: /etc/systemd/system/containerd.service.d
    state: directory
  when: ansible_service_mgr == 'systemd'

- name: Add shim to ensure Docker can start with systemd
  copy:
    dest: /etc/systemd/system/containerd.service.d/override.conf
    content: "[Service]\nExecStartPre="
  when: ansible_service_mgr == 'systemd'

- name: Ensure docker is started and enabled at boot
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure docker users are added to the docker group
  user:
    name: "{{ item.name }}"
    groups: docker
    append: true
  with_items: "{{ users }}"
